#!/bin/bash

cd constant
ln -s ../inner/transportProperties outer/transportProperties
ln -s ../inner/dynamicMeshDict outer/dynamicMeshDict
ln -s ../inner/rotationalMRFZones outer/rotationalMRFZones
ln -s ../inner/translationalMRFZones outer/translationalMRFZones

cd ../system
ln -s ../decomposeParDict outer/decomposeParDict
ln -s ../decomposeParDict inner/decomposeParDict
ln -s ../decomposeParDict solid/decomposeParDict

ln -s ../inner/faSchemes outer/faSchemes
ln -s ../inner/fvSchemes outer/fvSchemes
ln -s ../inner/faSolution outer/faSolution
ln -s ../inner/fvSolution outer/fvSolution

cd ..

