#!/bin/sh

cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


cp 0/fluid/orig/monolithic/T 0/fluid/.
cp 0/fluid/orig/monolithic/k 0/fluid/.
cp 0/solid/orig/monolithic/T 0/solid/.
cp 0/solid/orig/monolithic/k 0/solid/.

cp constant/fluid/polyMesh/blockMeshDictMonolithic constant/fluid/polyMesh/blockMeshDict 2>/dev/null
cp constant/solid/polyMesh/blockMeshDictMonolithic constant/solid/polyMesh/blockMeshDict 2>/dev/null

cp constant/regionInterfacePropertiesMonolithic constant/regionInterfaceProperties

runApplication -l log.blockMesh.solid blockMesh -region solid 2>/dev/null
runApplication -l log.setSet.solid setSet -region solid -batch solid.setSet 2>/dev/null
runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap 2>/dev/null

runApplication blockMesh -region fluid 2>/dev/null
runApplication setSet -region fluid -batch fluid.setSet 2>/dev/null
runApplication setsToZones -region fluid -noFlipMap 2>/dev/null

runApplication makeFaMesh -region fluid 2>/dev/null
runApplication -l log.makeFaMesh.solid makeFaMesh -region solid 2>/dev/null

./makeLinks fluid

runApplication multiRegionFoam 2>/dev/null 

runApplication sample -region fluid -latestTime 2>/dev/null 
