#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

vector="(5e-5 0 0)"

m4 < constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

runApplication blockMesh
transformPoints -translate "(5e-5 0 0)" > log.transformPoints
runApplication extrudeMesh
runApplication setSet -batch faces.setSet -noVTK
#runApplication setsToZones -noFlipMap
runApplication createPatch -overwrite
runApplication makeFaMesh
