#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Replace files in the main foam libraries
(cd filesToReplace && ./Allcheck)
if [ $? -ne 0 ]
then
    echo "Please fix the filesToReplaceInOF above!"
    exit 1
fi

wmakeLnInclude -f .

wmake libso src/loadBalancing

wmake application/solver/interLBDyMFoam
wmake application/utility/updateMesh
