#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get coupling method
couplingMethod=`cat system/coupledSolutionDict | grep 'couplingMethod' | tr -s ' ' | cut -d ' ' -f2 | tr -d ';' | tail -n1`

# -monolithic coupling method
if [ "$couplingMethod" == "monolithic" ]
then
  cp 0/fluid/orig/monolithic/T 0/fluid/.
  cp 0/fluid/orig/monolithic/alpha 0/fluid/.
  cp 0/solid/orig/monolithic/T 0/solid/.
  cp 0/solid/orig/monolithic/kS 0/solid/.

  cp constant/fluid/polyMesh/blockMeshDictMonolithic constant/fluid/polyMesh/blockMeshDict 2>/dev/null
  cp constant/solid/polyMesh/blockMeshDictMonolithic constant/solid/polyMesh/blockMeshDict 2>/dev/null

  runApplication -l log.blockMesh.solid blockMesh -region solid 2>/dev/null
  runApplication -l log.setSet.solid setSet -region solid -batch solid.setSet 2>/dev/null
  runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap 2>/dev/null

  runApplication blockMesh -region fluid 2>/dev/null
  runApplication setSet -region fluid -batch fluid.setSet 2>/dev/null
  runApplication setsToZones -region fluid -noFlipMap 2>/dev/null
fi

# -partitioned coupling method
if [ "$couplingMethod" == "partitioned" ]
then
  cp constant/fluid/polyMesh/blockMeshDictPartitioned constant/fluid/polyMesh/blockMeshDict 2>/dev/null
  cp constant/solid/polyMesh/blockMeshDictPartitioned constant/solid/polyMesh/blockMeshDict 2>/dev/null

  runApplication -l log.blockMesh.solid blockMesh -region solid 2>/dev/null
  runApplication blockMesh -region fluid 2>/dev/null

  cp 0/fluid/orig/partitioned/T 0/fluid/.
  cp 0/solid/orig/partitioned/T 0/solid/.
fi

runApplication conjugateHeatFoam 2>/dev/null

#decomposePar -region fluid 2>/dev/null
#decomposePar -region solid 2>/dev/null

#mpirun -np 2 conjugateHeatFoam -parallel
#runParallel conjugateHeatFoam 2
