#!/bin/sh
# This script must be invoked from the root directory of the repo

check_errs()
{
  # Parameter 1 is the return code
  # Parameter 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "ERROR # ${1} : ${2}"
    exit ${1}
  fi
}


libs="loadBalancing"
root=$PWD

# Test libraries
for lib in $libs; do
    echo "--------------------------------------------"
    echo "Testing library: $lib"
    echo "--------------------------------------------"
    cd $root/tests/$lib
    ./Allrun
    check_errs $? "Tests for $lib didn't pass ..."
    cd -
done
