#!/bin/sh
set -x

wcleanLnIncludeAll
rmdepall
rmoall

dependencies/movingReferenceFrame/Allwclean

wclean libso src/multiRegionSystem

wclean applications/solvers/conjugateHeatFoam
wclean applications/solvers/multiRegionFoam

