#!/bin/bash

source etc/bashrc

set -x

wmakeLnIncludeAll

#wmakeLnInclude -f .

#wmakeLnInclude -f src/.
ln -sf "$FOAM_UTILITIES/mesh/manipulation/mergeMeshes/mergePolyMesh.C" "src/multiRegionSystem/mergePolyMesh.C"
ln -sf "$FOAM_UTILITIES/mesh/manipulation/mergeMeshes/mergePolyMesh.H" "src/multiRegionSystem/mergePolyMesh.H"

( cd dependencies/movingReferenceFrame/ && ./Allwmake )
( cd dependencies/multiRegionFoam/ && ./Allwmake )
( cd dependencies/amrloadbalancing/ && ./Allwmake )

wmake libso src/dynamicFvMesh
wmake libso src/fvPatchFields
wmake libso src/fvSchemes

wmake applications/utilities/calcCurvature
wmake applications/utilities/checkFaMesh

# Replace files in the main foam libraries
(cd filesToReplace && ./Allcheck)
if [ $? -ne 0 ]
then
    echo "Please consider to fix the filesToReplaceInOF above if you want to cases wih AMR!"
    exit 1
fi
