#!/bin/sh
set -x

wmakeLnInclude -f .

wmakeLnInclude -f src/.
ln -sf "$FOAM_UTILITIES/mesh/manipulation/mergeMeshes/mergePolyMesh.C" "src/multiRegionSystem/mergePolyMesh.C"
ln -sf "$FOAM_UTILITIES/mesh/manipulation/mergeMeshes/mergePolyMesh.H" "src/multiRegionSystem/mergePolyMesh.H"

wmake libso src/multiRegionSystem

wmake applications/solvers/conjugateHeatFoam
wmake applications/solvers/multiRegionFoam
