#!/bin/sh
set -x

wcleanLnIncludeAll
rmdepall
rmoall

(cd dependencies/movingReferenceFrame/ && ./Allwclean )
(cd dependencies/thermoModels/ && ./Allwclean )

wclean libso src/coupledFvPatchFields

wclean libso src/multiRegionSystem

wclean applications/solvers/multiRegionFoam

