#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp 0/fluid/orig/partitioned/T 0/fluid/.
cp 0/solid/orig/partitioned/T 0/solid/.
cp 0/fluid/orig/partitioned/alpha 0/fluid/.
cp 0/solid/orig/partitioned/k 0/solid/.

./makeLinks fluid

#runApplication conjugateHeatFoam 2>/dev/null

#decomposePar -region fluid 2>/dev/null
#decomposePar -region solid 2>/dev/null

#mpirun -np 2 conjugateHeatFoam -parallel
#runParallel conjugateHeatFoam 2
