#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! $# == 1 ]; then
        echo "Missing options!"
        echo "(run $0 -p for partitioned"
        echo " or -m for monolithic)"
        echo ""
        exit 0
fi

while getopts "pm" OPTION; do
        case $OPTION in

        p)
	    cp constant/operatingConditions constant/cathodeCL/.
	    cp constant/operatingConditions constant/cathodeGDL/.
	    cp constant/operatingConditions constant/membrane/.

            cp 0/membrane/orig/partitioned/T 0/membrane/.
	    cp 0/membrane/orig/partitioned/phiP 0/membrane/.
	    cp 0/membrane/orig/partitioned/lambda 0/membrane/.

	    cp 0/cathodeCL/orig/partitioned/T 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/phiE 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/phiP 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/xO2 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/xV 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/lambda 0/cathodeCL/.
	    cp 0/cathodeCL/orig/partitioned/s 0/cathodeCL/.

	    cp 0/cathodeGDL/orig/partitioned/T 0/cathodeGDL/.
	    cp 0/cathodeGDL/orig/partitioned/phiE 0/cathodeGDL/.
	    cp 0/cathodeGDL/orig/partitioned/xO2 0/cathodeGDL/.
	    cp 0/cathodeGDL/orig/partitioned/xV 0/cathodeGDL/.
	    cp 0/cathodeGDL/orig/partitioned/s 0/cathodeGDL/.


            cp constant/membrane/polyMesh/blockMeshDictPartitioned constant/membrane/polyMesh/blockMeshDict 2>/dev/null
            cp constant/cathodeCL/polyMesh/blockMeshDictPartitioned constant/cathodeCL/polyMesh/blockMeshDict 2>/dev/null
	    cp constant/cathodeGDL/polyMesh/blockMeshDictPartitioned constant/cathodeGDL/polyMesh/blockMeshDict 2>/dev/null

  	    runApplication -l log.blockMesh.membrane blockMesh -region membrane 2>/dev/null
	    runApplication -l log.blockMesh.cathodeCL blockMesh -region cathodeCL 2>/dev/null
            runApplication -l log.blockMesh.cathodeGDL blockMesh -region cathodeGDL 2>/dev/null
  	    ;;

        m)
	    cp constant/operatingConditions constant/cathodeCL/.
	    cp constant/operatingConditions constant/cathodeGDL/.
	    cp constant/operatingConditions constant/membrane/.

            cp 0/membrane/orig/monolithic/T 0/membrane/.
            cp 0/membrane/orig/monolithic/phiP 0/membrane/.
            cp 0/membrane/orig/monolithic/lambda 0/membrane/.
	    #cp 0/membrane/orig/monolithic/k 0/membrane/.
            #cp 0/membrane/orig/monolithic/kappa 0/membrane/.
            #cp 0/membrane/orig/monolithic/DLambda 0/membrane/.

            cp 0/cathodeCL/orig/monolithic/T 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/phiE 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/phiP 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/xO2 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/xV 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/lambda 0/cathodeCL/.
            cp 0/cathodeCL/orig/monolithic/s 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/k 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/sigma 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/kappa 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/DO2Eff 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/DVEff 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/DLambda 0/cathodeCL/.
            #cp 0/cathodeCL/orig/monolithic/K 0/cathodeCL/.

            cp 0/cathodeGDL/orig/monolithic/T 0/cathodeGDL/.
            cp 0/cathodeGDL/orig/monolithic/phiE 0/cathodeGDL/.
            cp 0/cathodeGDL/orig/monolithic/xO2 0/cathodeGDL/.
            cp 0/cathodeGDL/orig/monolithic/xV 0/cathodeGDL/.
            cp 0/cathodeGDL/orig/monolithic/s 0/cathodeGDL/.
	    #cp 0/cathodeGDL/orig/monolithic/k 0/cathodeGDL/.
            #cp 0/cathodeGDL/orig/monolithic/sigma 0/cathodeGDL/.
            #cp 0/cathodeGDL/orig/monolithic/DO2Eff 0/cathodeGDL/.
            #cp 0/cathodeGDL/orig/monolithic/DVEff 0/cathodeGDL/.
            #cp 0/cathodeGDL/orig/monolithic/K 0/cathodeGDL/.

            cp constant/membrane/polyMesh/blockMeshDictMonolithic constant/membrane/polyMesh/blockMeshDict 2>/dev/null
            cp constant/cathodeCL/polyMesh/blockMeshDictMonolithic constant/cathodeCL/polyMesh/blockMeshDict 2>/dev/null
	    cp constant/cathodeGDL/polyMesh/blockMeshDictMonolithic constant/cathodeGDL/polyMesh/blockMeshDict 2>/dev/null

            runApplication -l log.blockMesh.membrane blockMesh -region membrane 2>/dev/null
            runApplication -l log.setSet.membrane setSet -region membrane -batch membrane.setSet 2>/dev/null
            runApplication -l log.setsToZones.membrane setsToZones -region membrane -noFlipMap 2>/dev/null

            runApplication -l log.blockMesh.cathodeCL blockMesh -region cathodeCL 2>/dev/null
            runApplication -l log.setSet.cathodeCL setSet -region cathodeCL -batch cathodeCL.setSet 2>/dev/null
            runApplication -l log.setsToZones.cathodeCL setsToZones -region cathodeCL -noFlipMap 2>/dev/null

	    runApplication -l log.blockMesh.cathodeGDL blockMesh -region cathodeGDL 2>/dev/null
            runApplication -l log.setSet.cathodeGDL setSet -region cathodeGDL -batch cathodeGDL.setSet 2>/dev/null
            runApplication -l log.setsToZones.cathodeGDL setsToZones -region cathodeGDL -noFlipMap 2>/dev/null
            ;;

        esac
done

./makeLinks membrane

runApplication multiRegionFoam 2>/dev/null

#decomposePar -region fluid 2>/dev/null
#decomposePar -region solid 2>/dev/null

#mpirun -np 2 conjugateHeatFoam -parallel
#runParallel conjugateHeatFoam 2
