#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

m4 < constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

(. $HOME/foam/OpenFOAM-plus/etc/bashrc
runApplication blockMesh
)

transformPoints -scale "(0.0005 0.0005 0.0005)" >> log.transformPoints
runApplication makeFaMesh
runApplication calcCurvature
