#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication createPatch -overwrite
runApplication splitMeshRegions -overwrite
cp -r constant/faMesh constant/domain1/faMesh
runApplication makeFaMesh -region domain1

