#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication ideasUnvToFoam constant/geometry/freeBubble.unv
runApplication polyDualMesh 75
runApplication improveMeshQuality
runApplication splitMeshRegions -overwrite
cp -r constant/faMesh constant/domain0/faMesh
runApplication makeFaMesh -region domain0
