#!/bin/sh
#------------------------------------------------------------------------------
echo 'Cleaning files'
find . \( -name 'VTK' \) -exec rm -rf {} \;
find . \( -name 'log' \) -exec rm -rf {} \;
find . \( -name 'postProcessing' \) -exec rm -rf {} \;
rm -rf [1-9]*
rm -rf 0.*
rm -rf *e-*
rm logs > /dev/null 2>&1
#find . \( -name 'polyMesh' \) -exec rm -rvf {} \;
#rm -vfr constant/polyMesh

echo ''
# ----------------------------------------------------------------- end-of-file
