#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Function for the checking and reporting how to fix file that needs to be fixed
# Arguments:
#   $1  - File name
#   $2  - Target path, without the file name and the slash at the end
#   $3  - Path to library to be re-built
#
checkAndReport()
{
    if cmp --silent "./${1}" "${2}/${1}"
    then
        echo "'${1}' has already been replaced"
        return 0
    else
        echo
        echo "******** PLEASE FIX THIS ***********"
        echo "You should replace the file '${2}/${1}' with 'filesToReplace/${1}'"
        echo
        echo "You can do it by running the following commands:"
        echo "    cp filesToReplace/${1} ${2}/"
        echo "    wmake libso ${3}"
        echo
        echo "These actions will not break your working foam-extend installation."
        echo "It will just fix some minor bugs in the listed file which need to "
        echo "be fixed in order to make multiRegionFoam work propperly."
        echo "************************************"
        echo
        return 1
    fi
}



# Check if the foam files have been replaced
echo "Check filesToReplace"

result=0

checkAndReport \
    "fvBlockMatrix.C" \
    "$FOAM_SRC/finiteVolume/fvMatrices/fvBlockMatrix" \
    "!Does not have to be executed!"
if [ $? -ne 0 ]; then result=1; fi

if [ "$result" -ne 0 ]
then
    echo
    echo "******** PLEASE FIX THIS ***********"
    echo "Please replace the files above"
    echo "************************************"
    echo
    exit 1
fi