#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

vector="(5e-5 0 0)"

m4 < constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

(. $HOME/foam/OpenFOAM-plus/etc/bashrc
runApplication blockMesh
)

transformPoints -scale "(0.0005 0.0005 0.0005)" > log.transformPoints
