#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! $# == 1 ]; then
        echo "Missing options!"
        echo "(run $0 -p for partitioned"
        echo " or -m for monolithic)"
        echo ""
        exit 0
fi

while getopts "pm" OPTION; do
        case $OPTION in

        p)
            cp 0/fluidA/orig/partitioned/U 0/fluidA/.
            cp 0/fluidB/orig/partitioned/U 0/fluidB/.
            
            cp 0/fluidA/orig/partitioned/p 0/fluidA/.
            cp 0/fluidB/orig/partitioned/p 0/fluidB/.

            cp constant/fluidA/polyMesh/blockMeshDictPartitioned constant/fluidA/polyMesh/blockMeshDict 2>/dev/null
            cp constant/fluidB/polyMesh/blockMeshDictPartitioned constant/fluidB/polyMesh/blockMeshDict 2>/dev/null

            runApplication -l log.blockMesh.fluidB blockMesh -region fluidB 2>/dev/null
            runApplication blockMesh -region fluidA 2>/dev/null
            
            #check
            runApplication -l log.setSet.fluidB setSet -region fluidB -batch faces.setSet 2>/dev/null
            runApplication setSet -region fluidA -batch faces.setSet 2>/dev/null
            
            #runApplication createPatch -overwrite
            
            transformPoints -scale "(0.004 0.001 0.001)" -region fluidA 2>/dev/null >> log.transformPoints
            transformPoints -scale "(0.004 0.001 0.001)" -region fluidB 2>/dev/null >> log.transformPoints
            
            runApplication makeFaMesh -region fluidA 2>/dev/null 
            runApplication -l log.makeFaMesh.fluidB makeFaMesh -region fluidB 2>/dev/null

            #runApplication calcCurvature
            ;;

        m)
            cp 0/fluid/orig/monolithic/T 0/fluid/.
            cp 0/fluid/orig/monolithic/alpha 0/fluid/.
            cp 0/solid/orig/monolithic/T 0/solid/.
            cp 0/solid/orig/monolithic/alpha 0/solid/.

            cp constant/fluid/polyMesh/blockMeshDictMonolithic constant/fluid/polyMesh/blockMeshDict 2>/dev/null
            cp constant/solid/polyMesh/blockMeshDictMonolithic constant/solid/polyMesh/blockMeshDict 2>/dev/null

            runApplication -l log.blockMesh.solid blockMesh -region solid 2>/dev/null
            runApplication -l log.setSet.solid setSet -region solid -batch solid.setSet 2>/dev/null
            runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap 2>/dev/null

            runApplication blockMesh -region fluid 2>/dev/null
            runApplication setSet -region fluid -batch fluid.setSet 2>/dev/null
            runApplication setsToZones -region fluid -noFlipMap 2>/dev/null
            ;;


        esac
done

./makeLinks fluidA

runApplication multiRegionFoam 2>/dev/null

#decomposePar -region fluid 2>/dev/null
#decomposePar -region solid 2>/dev/null

#mpirun -np 2 conjugateHeatFoam -parallel
#runParallel conjugateHeatFoam 2
