{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    For further information on multiRegionFoam, please see the               |\n"
        << "|    following publication:                                                   |\n"
        << "|                                                                             |\n"
        << "|    Alkafri, H., Habes, C., Fadeli, M. E., Hess, S., Beale, S. B.,           |\n"
        << "|    Zhang, S., Jasak, H., & Marschall, H. (2023).                            |\n"
        << "|    multiRegionFoam -- A Unified Multiphysics Framework for Multi-Region     |\n"
        << "|    Coupled Continuum-Physical Problems (Version 1). arXiv.                  |\n"
        << "|    https://doi.org/10.48550/ARXIV.2306.01924                                |\n"
        << "|                                                                             |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}

