#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

vector="(1e-5 0 0)"

m4 < constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

runApplication blockMesh
transformPoints -translate "(1e-3 0 0)" > log.transformPoints
runApplication extrudeMesh
runApplication setSet -batch faces.setSet
runApplication createPatch -overwrite
transformPoints -scale "(0.004 0.001 0.001)" >> log.transformPoints
runApplication makeFaMesh
runApplication calcCurvature
