#!/bin/sh

find -type l -delete

rm -rf 0.* [1-9]* log* proc* VTK

rm -rf constant/fluidA/polyMesh 2>/dev/null
rm -rf constant/fluidB/polyMesh 2>/dev/null

rm -rf constant/fluidA/faMesh 2>/dev/null
rm -rf constant/fluidB/faMesh 2>/dev/null

rm 0/fluidA/U 2>/dev/null
rm 0/fluidA/p 2>/dev/null

rm 0/fluidB/U 2>/dev/null
rm 0/fluidB/p 2>/dev/null

