#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source more run functions
. $LBAMR_PROJECT/scripts/moreRunFunctions

backup=constant/dynamicMeshDict.$(date +"%s")
maxRefinement=$(setDynamicMeshDictForMeshUpdate $backup)

trap "onCtrl_C $backup" INT

nProcs=$(getNumberOfProcessors)

#import gmsh
runApplication gmshToFoam damBreak.msh

#combine prisms to polyhedrals
runApplication polyDualMesh 60 -concaveMultiCells -overwrite

runApplication extrudeMesh
runApplication autoPatch 90 -overwrite
runApplication createPatch -overwrite

runApplication checkMesh

cp -r 0.orig 0
runApplication setFields

for i in $( seq 1 $maxRefinement )
do
  runApplication -a setFields #-time 0

  runApplication -a updateMesh -overwrite
done

runApplication -a setFields #-time 0


runApplication decomposePar -cellDist

resetDynamicMeshDict $backup

#ENVLIST=$(echo $WM_PROJECT_DIR)/etc/env
#EVAR=$(for e in $(cat $ENVLIST); do echo "-x $e " ; done)

MPIRUN_OPTIONS="--bind-to core --map-by core --report-bindings"

#runParallel interDyMLBFoam
mpirun $MPIRUN_OPTIONS -np 2 interLBDyMFoam -parallel > log.interLBDyMFoam