#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source tutorial run functions
. $LBAMR_PROJECT/scripts/moreRunFunctions

backup=constant/dynamicMeshDict.$(date +"%s")
maxRefinement=$(setDynamicMeshDictForMeshUpdate $backup)

trap "onCtrl_C $backup" INT

nProcs=$(getNumberOfProcessors)

cp -r 0.org 0

runApplication blockMesh
runApplication setFields

for i in $( seq 1 $maxRefinement )
do
  runApplication -a setFields #-time 0
  runApplication -a updateMesh -overwrite
done

runApplication -a setFields #-time 0


runApplication decomposePar -cellDist -force
#decomposePar -cellDist -force -region tempMesh
runApplication decomposeParLevel

resetDynamicMeshDict $backup

#for dir in processor*/; do mkdir -- "$dir/constant"; done
#for i in $(seq 0 1 $((nProcs-1))); do cp -r ./constant/* processor$i/constant/; done

#runParallel interLBDyMFoam
mpirun -np 4 interLBDyMFoam -parallel > log.interLBDyMFoam &

# ----------------------------------------------------------------- end-of-file
