#!/bin/sh
#------------------------------------------------------------------------------
echo 'Generating meshes: Output in blockMesh.log'
blockMesh > blockMesh.log
topoSet > topoSet.log
splitMeshRegions -cellZonesOnly -overwrite > splitMeshRegions.log
echo 'Changing patch type to symmetry in /polyMesh/boundary'
sed -i '29s/patch/symmetry/' constant/fluid/polyMesh/boundary
#echo 'Running case'
#myChtMultiRegionSimpleFoam | tee myLog
#echo 'Done'
# ----------------------------------------------------------------- end-of-file
