#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf \
    constant/*/polyMesh \
    constant/polyMesh \
    constant/extendedFeatureEdgeMesh \
    constant/triSurface/*.eMesh
    
rm -r times/*
rm -r *.png

rm -r constant/*/cellID
rm -r constant/*/faMesh
rm -r constant/*/cellToRegion
rm -r 0/cellToRegion
rm -r *.pdf

#------------------------------------------------------------------------------
