#!/bin/sh

# run from this directory
cd ${0%/*} || exit 1

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r 0
#remove merged meshes
rm -r constant/polyMesh/*

cleanCase
# ----------------------------------------------------------------- end-of-file