#!/bin/sh

find -type l -delete

rm -rf 0.* [1-9]* log* proc* VTK

rm constant/fluid/polyMesh/blockMeshDict 2>/dev/null
rm constant/solid/polyMesh/blockMeshDict 2>/dev/null

rm 0/fluid/T 2>/dev/null
rm 0/fluid/alpha 2>/dev/null

rm 0/solid/T 2>/dev/null
rm 0/solid/alpha 2>/dev/null
