#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

# Compile and run tests
echo "Compiling test driver"
if ! wmake > log.wmake 2>&1; then
    echo "Errors compiling, see $PWD/log.wmake for more information"
    return 1
fi

# Get cases
rm -rf testData
cp -r ../cases/damBreak testData

echo "Running tests"
# Run serial tests
cd testData; ../loadBalancingNewTestDriver "[Serial]" $CATCH_SERIAL_OPTIONS ; cd -

# Run parallel tests
cd testData
decomposePar > log.decomposePar
mpirun -np 2 --output-filename parallelTests.xml ../loadBalancingNewTestDriver --parallel "[Parallel]" $CATCH_PARALLEL_OPTIONS
cd -
