#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

find -type l -delete

rm constant/fluidA/polyMesh/blockMeshDict 2>/dev/null
rm constant/fluidB/polyMesh/blockMeshDict 2>/dev/null

rm constant/fluidA/polyMesh/boundary 2>/dev/null
rm constant/fluidB/polyMesh/boundary 2>/dev/null

rm constant/fluidA/faMesh/faceLabels 2>/dev/null
rm constant/fluidB/faMesh/faceLabels 2>/dev/null

rm constant/fluidA/faMesh/faBoundary 2>/dev/null
rm constant/fluidB/faMesh/faBoundary 2>/dev/null

rm 0/fluidA/U 2>/dev/null
rm 0/fluidB/U 2>/dev/null

rm 0/fluidA/p 2>/dev/null
rm 0/fluidB/p 2>/dev/null

rm 0/fluidA/pointMotionU 2>/dev/null
rm 0/fluidB/pointMotionU 2>/dev/null

