#!/bin/sh

#1. deleting lines which have the keyword "physicalType" in them
#2. in the different ranges betwee /start/,/stop/ substitue and add different entries

sed -i \
	-e 	'/physicalType.* / d' \
	-e  '/frontAndBack/,/}/ {
			s/patch/empty/
		}' \
	-e  '/insideSlider/,/}/ {
			s/patch/ggi/
			/type/a \		shadowPatch     outsideSlider;
			/type/a \		zone            insideZone;
			/type/a \		bridgeOverlap   false;
		}' \
	-e  '/impellerWall/,/}/ {
			s/patch/wall/
		}' \
	-e  '/substrate/,/}/ {
			s/patch/wall/
		}' \
	-e  '/baffleWall/,/}/ {
			s/patch/wall/
		}' \
	-e  '/outsideSlider/,/}/ {
			s/patch/ggi/
			/type/a \		shadowPatch     insideSlider;
			/type/a \		zone            outsideZone;
			/type/a \		bridgeOverlap   false;
		}' \
	-e  '/blade/,/}/ {
			s/patch/wall/
		}' \
		../constant/polyMesh/boundary
