#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh 2>/dev/null
./setSet.script 2>/dev/null
runApplication setsToZones
runApplication splitMeshRegions -cellZonesOnly -overwrite
find . -name "cellToRegion" -delete
runApplication -l log.setSet_fluid setSet -region fluid -batch fluidSetSet.batch
runApplication -l log.setSet_solid setSet -region solid -batch solidSetSet.batch
runApplication -l log.setToZones_fluid setsToZones -region fluid
runApplication -l log.setToZones_solid setsToZones -region solid

runApplication -l log.sedBCs_fluid sed -i \
's/directMappedWall/wall/;56,59d' \
constant/fluid/polyMesh/boundary

runApplication -l log.sedBCs_solid sed -i \
's/directMappedWall/wall/;56,59d' \
constant/solid/polyMesh/boundary

mv constant/polyMesh constant/polyMesh_whole
./makeLinks fluid

runApplication -l log.decomposePar_fluid decomposePar -region fluid
runApplication -l log.decomposePar_solid decomposePar -region solid

mpirun -np 4 multiRegionFoam -noFunctionObjects -parallel 2>&1 > log.multiRegionFoam 
