#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh 2>/dev/null
./setSet.script 2>/dev/null
runApplication setsToZones
runApplication splitMeshRegions -cellZonesOnly -overwrite
find . -name "cellToRegion" -delete

runApplication -l log.sedBCs_fluid sed -i '28s/patch/symmetryPlane/;22s/patch/wall/;s/directMappedWall/wall/;49,52d' constant/fluid/polyMesh/boundary
runApplication -l log.sedBCs_solid sed -i 's/patch/wall/g;s/directMappedWall/wall/;49,52d' constant/solid/polyMesh/boundary

mv constant/polyMesh constant/polyMesh_whole
./makeLinks fluid

runApplication -l log.decomposePar_fluid decomposePar -region fluid
runApplication -l log.decomposePar_solid decomposePar -region solid

mpirun -np 4 multiRegionFoam -noFunctionObjects -parallel 2>&1 > log.multiRegionFoam 
