#!/bin/bash
b=0.001905
p=0.001054
l=0.002833
d=0.0001016

x0=0
x1=$l
x2=`awk "BEGIN {l=$l; x2=2.0*l; print x2}"`
y0=0;
y1=`awk "BEGIN {d=$d; y1=0.5*d; print y1}"`
y2=`awk "BEGIN {d=$d; p=$p; y2=0.5*(p-d); print y2}"`
y3=`awk "BEGIN {p=$p; y3=0.5*p; print y3}"`
z0=0
z1=$d
z2=`awk "BEGIN {b=$b; d=$d; z2=b-d; print z2}"`
z3=$b