#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanFaMesh ()
{
    rm -rf ./constant/faMesh/faceLabels* \
           ./constant/faMesh/faBoundary* \
           > /dev/null 2>&1
}

cleanMesh()
{
    rm -rf ./constant/polyMesh/boundary \
           ./constant/polyMesh/*.gz \
        > /dev/null 2>&1
}

cd meshA;
cleanTimeDirectories;
cleanCase;
cleanMesh;
cleanFaMesh;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history 

cd ../meshB;
cleanTimeDirectories;
cleanCase;
cleanMesh;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history

cd ..
./removeSerialLinks meshA meshB

