#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="interTrackFoam"

# copy mesh from geometry folder
cd meshA/ 
./Allrun

cd ../meshB
./Allrun

cd ..
./makeSerialLinks meshA meshB

(cd meshA ; runApplication $application)
